name: north_america_heatwave
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - cartopy=0.23.0
  - geopandas=0.14.2
  - geopandas-base=0.14.2
  - matplotlib=3.8.4
  - matplotlib-base=3.8.4
  - numpy=1.26.4
  - numpy-base=1.26.4
  - pandas=2.2.2
  - python=3.12.3
  - scikit-learn=1.5.0
  - scipy=1.11.4
  - tqdm=4.66.5
  - xarray=2024.5.0
